name: Send Test Email

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email via SendGrid API
        run: |
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer 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" \
            --header "Content-Type: application/json" \
            --data '{
              "personalizations": [{"to": [{"email": "stanic.timotej1@gmail.com"}]}],
              "from": {"email": "stanic.timotej1@gmail.com"},
              "subject": "Test email iz GitHub Actions",
              "content": [{"type": "text/plain", "value": "Sistem deluje!"}]
            }'
